en:
  languageName: English
  weight: 1
  ### copyright (markdown can be used) ###
  copyright: "Copyright &copy; {{< current_year >}} WashU Epigenome Browser Team."
  title: "WashU Epigenome Browser Support"
  params:
    # description: "Site Description"
    ### accessibility ###
    # accessibility:
    #   skip_text: "Skip to content"
    #   help_text: "Accessibility Statement"
    #   help_url: "/example-page/"
    ### calls to action ###
    # main_cta:
    #   text: "Join"
    #   link: "/example-page/"
    # footer_cta:
    #   text: "Join us"
    #   link: "/example-page/"
    github_edit: "Edit this page on GitHub"
  ### example menu showing children ###
  menu:
    main:
    # - identifier: "workshops"
    #   name: "Workshops"
    #   url: "/workshops/"
    #   weight: 1
    # - identifier: "2025-fudan-workshop"
    #   name: "2025 Fudan Workshop"
    #   url: "/2025-fudan-workshop/"
    #   weight: 1
    #   # post: "Nulla consequat massa quis enim. Donec pede justo."
    #   parent: "workshops"
    
    # - identifier: "demo-page"
    #   name: "Demo Page"
    #   url: "/demo-page/"
    #   weight: 2
    # - identifier: "faq"
    #   name: "FAQs"
    #   url: "/faq/"
    #   weight: 3
    - identifier: "workshops"
      name: "Workshops"
      url: "/workshops/"
      weight: 4
    - identifier: "documentation"
      name: "Documentation"
      url: "https://epgg.github.io/"
      weight: 5
# es:
#   languageName: Spanish
#   contentDir: content/es
#   weight: 2
#   title: "Título del Sitio"
#   params:
#     description: "Descripción del Sitio"
#   menu:
#     main:
#     - identifier: "about"
#       name: "Acerca de"
#       url: "/example-page/"
#       weight: 1
#     - identifier: "child-1"
#       name: "Página Hija de Ejemplo"
#       url: "/example-page/"
#       weight: 1
#       parent: "about"
#     - identifier: "faq"
#       name: "FAQs"
#       url: "/faq/"
#       weight: 3
#     - identifier: "blog"
#       name: "Blog"
#       url: "/blog/"
#       weight: 2
